Update deploy-snowflake-prod.yml

diff --git a/.github/workflows/deploy-snowflake-prod.yml b/.github/workflows/deploy-snowflake-prod.yml
--- a/.github/workflows/deploy-snowflake-prod.yml
+++ b/.github/workflows/deploy-snowflake-prod.yml
@@ -1,27 +1,44 @@
-name: Create PR from DEV to PROD
- 
+name: snowflake-devops-demo
 on:
   push:
     branches:
-      - DEV
+      - PROD
     paths:
       - 'dbscripts2/**'
- 
+  pull_request:
+    branches:
+      - PROD
+  workflow_dispatch:
 jobs:
-  create-pr-from-dev:
+  deploy-snowflake-changes-job:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
- 
-      - name: Set up GitHub Token
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.8
+      - name: Install dependencies
         run: |
-          git config --global user.email "actions@github.com"
+          pip install snowflake-connector-python
+      - name: Deploy SQL files, Archive, and Clean up
+        env:
+          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
+          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
+          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
+          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
+          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
+          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
+        run: |
+          python deploy_sql_files.py  # Deploy + archive + cleanup
+      - name: Commit & Push changes
+        env:
+          TOKEN: ${{ secrets.PAT_TOKEN }}
+        run: |
           git config --global user.name "github-actions"
- 
-          curl -X POST \
-            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-            -d '{"title":"Automated PR from DEV to PROD","head":"DEV","base":"PROD"}' \
-            "https://api.github.com/repos/${{ github.repository }}/pulls"
+          git config --global user.email "actions@github.com"
+          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
+          git add .
+          git commit -m "Auto deploy, archive old versions, and clean up archive" || echo "No changes"
+          git push
