Update deploy-snowflake-prod.PROD.yml

diff --git a/.github/workflows/deploy-snowflake-prod.PROD.yml b/.github/workflows/deploy-snowflake-prod.PROD.yml
--- a/.github/workflows/deploy-snowflake-prod.PROD.yml
+++ b/.github/workflows/deploy-snowflake-prod.PROD.yml
@@ -1,5 +1,4 @@
 name: snowflake-devops-demo
-
 on:
   push:
     branches:
@@ -10,27 +9,19 @@ on:
     branches:
       - PROD
   workflow_dispatch:
-
 jobs:
   deploy-snowflake-changes-job:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
-
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: 3.8
-
       - name: Install dependencies
         run: |
           pip install snowflake-connector-python
-
-      - name: Install GitHub CLI
-        run: sudo apt-get install gh -y
-
       - name: Deploy SQL files, Archive, and Clean up
         env:
           SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
@@ -40,25 +31,14 @@ jobs:
           SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
           SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
         run: |
-          python deploy_sql_files.py
-
-      - name: Commit & Push changes to new branch and create PR
+          python deploy_sql_files.py  # Deploy + archive + cleanup
+      - name: Commit & Push changes
         env:
           TOKEN: ${{ secrets.PAT_TOKEN }}
         run: |
-          TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
-          BRANCH_NAME="auto/update-archive-$TIMESTAMP"
-
           git config --global user.name "github-actions"
           git config --global user.email "actions@github.com"
-          git checkout -b $BRANCH_NAME
-
+          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
           git add .
-          git commit -m "Auto deploy, archive old versions, and clean up archive" || echo "No changes to commit"
-          git push -u origin $BRANCH_NAME
-
-          echo "${TOKEN}" | gh auth login --with-token
-          gh pr create --title "Automated deployment update $TIMESTAMP" \
-                       --body "This PR contains automatic archive/cleanup changes." \
-                       --base PROD \
-                       --head $BRANCH_NAME
+          git commit -m "Auto deploy, archive old versions, and clean up archive" || echo "No changes"
+          git push
